language: go
go:
- '1.10'
script:
- make
before_deploy:
- make VERSION=${TRAVIS_TAG} release
deploy:
  provider: releases
  api_key:
    secure: ''
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: LKL2jQUr6MaFO+GFPOLXHy2k6/2p8xrJRZl8V56aGfKfWsKRsZhNX/O0e3Uh/3bSkcMsO1FaSilu0PLy3+Wyb00WdcKho4It1ZsQ4rTsJHJv30OCJXj/lq43unKp/BvQphytFatV0P9Ode0zUYle8SVf+LZQri+CtdM9O31EWD1ni+ZS3qvng5c3qJIqTZ2h1yxYrA9p+vw2KFF96NV1UfV4ZwDb+K1nSGETFwe0HqDJ42tr2qC9NUUmWoUsUjAwEZ4vsMtj2APBY0899upGgTx/YZVtFltUMD3yfu74tdUVmghirByRFyhMFdEz+/1SH6Tgg+MiSLAVqv2puvTJv3NcCS7aSi63EIOo1hauRzCK6PCQd2D9R1mXzY+W4hkpcVRHjMweOKV8OKODtKQjaYJVPo8KIGw5LhffVvf1MwTXTJffhHl0Ayp1ww7BY9Blxzl9vvjJqmVmIFtA18Lug0svMjaCD+yjb6II1ZOK+igCuVN5Kr0p/9Osv0kiW72TGlTrOMlfase362/XZ+BwzPkLtzbgLjjTPC2UxGOo3MnC3amhxKGd3C19rzzp4pGySxTR9B9ujxyksIXnlF3c/POKGStjWuRllC+2pg/S/30BoMAkNUt15XKqWD+uUTPNoDPhpdz39RUbPGjeUCYuyY6hzgj69xYoi8FD/ohpZVg=
